# Generated by Django 5.1.4 on 2026-02-08 12:45

import files.models
import files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_alter_file_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(storage=files.storage.MixedMediaCloudinaryStorage(), upload_to=files.models.user_directory_path),
        ),
    ]
